income/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = "income"

urlpatterns = [
    # path("users/", include("users.urls")),
    path('', views.index_view.as_view(), name='index'),
    path('income/', views.income_view.as_view(), name='income'),

    ]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from income import views

urlpatterns = [
    # path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
    path('', include("income.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = "polls"
urlpatterns = [
    path('', views.index_view.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("create_q/", views.create_q, name="create_q"),
]

income/models.py
from django.db import models

from general.models import BaseAbstractModel, Route, Car, CommonSelect, Employee


class IncomeData(BaseAbstractModel):
    id = models.AutoField(primary_key=True)

    date = models.DateField(verbose_name='날짜')

    route = models.ForeignKey(to=Route,
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True,
                              verbose_name='노선')

    car = models.ForeignKey(to=Car,
                            on_delete=models.SET_NULL,
                            null=True,
                            blank=True,
                            verbose_name='차량')

    save_is_profit = models.BooleanField(null=True,
                                         blank=True,
                                         verbose_name='수익노선여부')

    save_work_type_a = models.ForeignKey(to=CommonSelect,
                                         on_delete=models.SET_NULL,
                                         null=True,
                                         blank=True,
                                         related_name='income_work_type_a',
                                         verbose_name='시점근무타입A')

    save_work_type_b = models.ForeignKey(to=CommonSelect,
                                         on_delete=models.SET_NULL,
                                         null=True,
                                         blank=True,
                                         related_name='income_work_type_b',
                                         verbose_name='시점근무타입B')

    emp_a = models.ForeignKey(to=Employee,
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True,
                              related_name='income_emp_a',
                              verbose_name='승무주임A')

    emp_b = models.ForeignKey(to=Employee,
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True,
                              related_name='income_emp_b',
                              verbose_name='승무주임B')

    reserve_funds = models.IntegerField(default=0,
                                        null=True,
                                        blank=True,
                                        verbose_name='고정예비금')

    reserve_balance = models.IntegerField(default=0,
                                          null=True,
                                          blank=True,
                                          verbose_name='예비금잔액')

    cash_10 = models.IntegerField(default=0,
                                  null=True,
                                  blank=True,
                                  verbose_name='10원')

    cash_50 = models.IntegerField(default=0,
                                  null=True,
                                  blank=True,
                                  verbose_name='50원')

    cash_100 = models.IntegerField(default=0,
                                   null=True,
                                   blank=True,
                                   verbose_name='100원')

    cash_500 = models.IntegerField(default=0,
                                   null=True,
                                   blank=True,
                                   verbose_name='500원')

    cash_paper = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='지폐금액')

    cash_1000 = models.IntegerField(default=0,
                                    null=True,
                                    blank=True,
                                    verbose_name='1,000원')

    cash_5000 = models.IntegerField(default=0,
                                    null=True,
                                    blank=True,
                                    verbose_name='5,000원')

    cash_10000 = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='10,000원')

    cash_50000 = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='50,000원')

    card_smt = models.IntegerField(default=0,
                                   null=True,
                                   blank=True,
                                   verbose_name='교통카드결제금액')

    card_transfer = models.IntegerField(default=0,
                                        null=True,
                                        blank=True,
                                        verbose_name='교통카드환승금액')

    note = models.CharField(max_length=150,
                            null=True,
                            blank=True,
                            verbose_name='비고')

    @property
    def get_cash_total(self):
        paper = self.cash_paper if self.cash_paper else 0
        funds = self.reserve_funds if self.reserve_funds else 0
        balance = self.reserve_balance if self.reserve_balance else 0
        c_500 = self.cash_500 if self.cash_500 else 0
        c_100 = self.cash_100 if self.cash_100 else 0
        c_10 = self.cash_10 if self.cash_10 else 0
        c_50 = self.cash_50 if self.cash_50 else 0
        result = (paper + c_500 + c_100 + c_10 + c_50) - (funds - balance)
        return result


# 레거시 모델 -------------------------------------------------------------------------------------------------------------
class Income(models.Model):
    """
    date = models.DateField(null=True)  # 일자
    route = models.ForeignKey(Route, models.CASCADE, null=True)
    car = models.ForeignKey(Car, models.DO_NOTHING, null=True)  # 차량 외부키
    employee = models.ForeignKey(Employee, models.DO_NOTHING, null=True)
    vaultCash = models.IntegerField(default=0)      # 예비금 잔액
    income_10 = models.IntegerField(default=0)
    income_50 = models.IntegerField(default=0)
    income_100 = models.IntegerField(default=0)
    income_500 = models.IntegerField(default=0)
    income_paper = models.IntegerField(default=0)
    income_smt = models.IntegerField(default=0)
    income_smt_transfer = models.IntegerField(default=0)
    income_total = models.IntegerField(default=0)
    # 예비금 추가 - 2021-12-10
    reserveFunds = models.IntegerField(default=0)
    dispatchMark = models.CharField(max_length=10, default="전일")  # 근태일지 표시용
    remarks = models.CharField(max_length=50, default='', null=True, blank=True)  # 비고
    # 비수익 노선 추가
    profit_List = ((False, '수익'), (True, '비수익'))
    non_profit_bus = models.BooleanField(choices=profit_List, default=False, blank=True)  # 비수익 노선
    class Meta:
        indexes = [
            models.Index(fields=["date", ]),
            models.Index(fields=["vaultCash", "income_10", "income_50", "income_100", "income_500",
                                 "income_smt", "income_smt_transfer", "income_total", "reserveFunds", "remarks",
                                 "non_profit_bus"]),
        ]
    """
    id = models.AutoField(primary_key=True)

    date = models.DateField(null=True,
                            blank=True,
                            verbose_name='날짜')

    route = models.ForeignKey(to=Route,
                              on_delete=models.SET_NULL,
                              null=True,
                              blank=True,
                              verbose_name='노선')

    car = models.ForeignKey(to=Car,
                            on_delete=models.SET_NULL,
                            null=True,
                            blank=True,
                            verbose_name='차량')

    employee = models.ForeignKey(to=Employee,
                                 on_delete=models.SET_NULL,
                                 null=True,
                                 blank=True,
                                 verbose_name='운수직')

    vaultCash = models.IntegerField(default=0,
                                    null=True,
                                    blank=True,
                                    verbose_name='')

    income_10 = models.IntegerField(default=0,
                                    null=True,
                                    blank=True,
                                    verbose_name='')

    income_50 = models.IntegerField(default=0,
                                    null=True,
                                    blank=True,
                                    verbose_name='')

    income_100 = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='')

    income_500 = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='')

    income_paper = models.IntegerField(default=0,
                                       null=True,
                                       blank=True,
                                       verbose_name='')

    income_smt = models.IntegerField(default=0,
                                     null=True,
                                     blank=True,
                                     verbose_name='')

    income_smt_transfer = models.IntegerField(default=0,
                                              null=True,
                                              blank=True,
                                              verbose_name='')

    income_total = models.IntegerField(default=0,
                                       null=True,
                                       blank=True,
                                       verbose_name='')

    reserveFunds = models.IntegerField(default=0,

income/views.py
from django.db.models import Sum, F, Avg, ExpressionWrapper, IntegerField, Value
from django.views.generic import TemplateView
from itertools import chain
from income.models import IncomeData
from general.models import Route


class index_view(TemplateView):
    template_name = 'income/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        return context


class income_view(TemplateView):
    template_name = 'income/income.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        income = IncomeData.objects.all()

        route = Route.objects.all().order_by('route_number')
        print(route)

        search_date_required = self.request.GET.get('search_date_required')
        select_route = self.request.GET.get('select_route')
        is_profit = self.request.GET.get('is_profit')
        print(f"search_date_required = {search_date_required}")
        print(f"select_route = {select_route}")
        print(f"is_profit = {is_profit}")

        if select_route != '' and is_profit != '':
            search_result = income.filter(route_id=select_route, save_is_profit=is_profit, date=search_date_required)
        elif is_profit != '':
            search_result = income.filter(date=search_date_required)
        elif select_route != '':
            search_result = income.filter(route_id=select_route, date=search_date_required)
        else:
            search_result = income.filter(date=search_date_required)

        search_result = search_result.annotate(
            coin_tot=ExpressionWrapper(F('cash_10') + F('cash_50') + F('cash_100')
                                       + F('cash_500'), output_field=IntegerField()),
            income_tot=ExpressionWrapper(F('cash_10') + F('cash_50') + F('cash_100') + F('cash_500')
                                         + F('cash_paper') + F('card_smt') + F('card_transfer')
                                         - F('reserve_funds') + F('reserve_balance'), output_field=IntegerField()),
            reverse_diff=ExpressionWrapper(-F('reserve_funds') + F('reserve_balance'), output_field=IntegerField()))

        Sum_result = (search_result.values('route__route_number').annotate(
            all_card_smt=Sum('card_smt'),
            all_card_transfer=Sum('card_transfer'),
            all_coin_tot=Sum('coin_tot'),
            all_cash_paper=Sum('cash_paper'),
            all_income_tot=Sum('income_tot'))
        )

        # test = search_result.filter(route__route_number=100).values('route__route_number').aggregate(Avg('card_smt'))
        # print(test)

        Avg_result = (search_result.values('route__route_number').annotate(
            avg_card_smt=ExpressionWrapper(Avg('card_smt'), output_field=IntegerField()),
            avg_card_transfer=ExpressionWrapper(Avg('card_transfer'), output_field=IntegerField()),
            avg_coin_tot=ExpressionWrapper(Avg('coin_tot'), output_field=IntegerField()),
            avg_cash_paper=ExpressionWrapper(Avg('cash_paper'), output_field=IntegerField()),
            avg_income_tot=ExpressionWrapper(Avg('income_tot'), output_field=IntegerField()))
        )

        combine_list = []
        for row in route:
            a = search_result.filter(route_id=row)
            b = Sum_result.filter(route_id=row)
            c = Avg_result.filter(route_id=row)
            combine_list = list(chain(combine_list, a))
            combine_list = list(chain(combine_list, b))
            combine_list = list(chain(combine_list, c))

        context['search_result'] = combine_list
        context['route'] = route

        return context

income/templates/income/income.html
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
<link rel="stylesheet" href="{% static 'css/style.css' %}?v=2">

<form action="{% url 'income:income' %}" class="row gy-2 gx-3 align-items-center" hx-push-url="true" hx-get="/income/" hx-target="#content_load">
    <div class="col-auto">
        <input type="date" name="search_date_required" class="form_control" required>
    </div>

    <div class="col-auto">
        <select name="select_route" class="form_control">
            <option value="">노선 전체</option>
            {% for row in route %}
                <option value="{{row.id}}">{{ row }}</option>
            {% endfor %}
        </select>
    </div>

    <div class="col-auto">
        <select name="is_profit" class="form_control">
            <option value="">영리구분 전체</option>
            <option value="1">수익</option>
            <option value="0">비수익</option>
        </select>
    </div>

    <div class="col-auto">
        <button type='submit' class="btn btn-outline-primary btn-sm col_min" >조회</button>
    </div>

</form>

<div class="overflow-auto">
<table class="income_table">
    <thead>
        <tr>
            <th>노선</th>
            <th>승무주임A</th>
            <th>승무주임B</th>
            <th>교통카드</th>
            <th>환승금</th>
            <th>동전</th>
            <th>지폐</th>
            <th>수지금액</th>
            <th>예비금차액</th>
        </tr>
    </thead>
    <tbody>
        {% for row in search_result %}
            {% if row.avg_card_smt %}
                <tr>
                    <td style="background-color: #faffeb" colspan="3">평균</td>
                    <td style="background-color: #faffeb">{{ row.avg_card_smt }}</td>
                    <td style="background-color: #faffeb">{{ row.avg_card_transfer }}</td>
                    <td style="background-color: #faffeb">{{ row.avg_coin_tot }}</td>
                    <td style="background-color: #faffeb">{{ row.avg_cash_paper }}</td>
                    <td style="background-color: #faffeb">{{ row.avg_income_tot }}</td>
                    <td style="background-color: #faffeb"></td>
                </tr>
            {% elif row.all_card_smt %}
                <tr>
                    <td style="background-color: #fEf2f2" colspan="3">합계</td>
                    <td style="background-color: #fEf2f2">{{ row.all_card_smt }}</td>
                    <td style="background-color: #fEf2f2">{{ row.all_card_transfer }}</td>
                    <td style="background-color: #fEf2f2">{{ row.all_coin_tot }}</td>
                    <td style="background-color: #fEf2f2">{{ row.all_cash_paper }}</td>
                    <td style="background-color: #fEf2f2">{{ row.all_income_tot }}</td>
                    <td style="background-color: #fEf2f2"></td>
                </tr>
            {% else %}
                <tr>
                    <td>{{ row.route }}</td>
                    <td>{{ row.emp_a }}</td>
                    <td>{% if row.emp_b %}
                        {{ row.emp_b }}
                        {% else %}
                        {% endif %}</td>
                    <td>{{ row.card_smt }}</td>
                    <td>{{ row.card_transfer }}</td>
                    <td>{{ row.coin_tot }}</td>
                    <td>{{ row.cash_paper }}</td>
                    <td>{{ row.income_tot }}</td>
                    <td>{{ row.reverse_diff }}</td>
                </tr>
            {% endif %}
        {% endfor %}

    </tbody>
</table>
</div>

income/templates/income/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://code.jquery.com/jquery-latest.min.js"></script>

    <script src="https://unpkg.com/htmx.org@1.9.5"
            integrity="sha384-xcuj3WpfgjlKF+FXhSQFQ0ZNr39ln+hwjN3npfM9VBnUskLolQAcN80McRIVOPuO"
            crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org/dist/ext/response-targets.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}?v=2">
</head>

<body>

    <aside id="aside">
        <div class="sidebar">
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">수입금관리</span>
                </button>
                <div class="aside_collapse">
                    <div class="aside_div">
                        <a class="aside_a text-black">수입금 등록</a>
                        <a class="aside_a text-black">수입금 현황</a>
                        <a class="aside_a text-black" href="/income/" hx-get="/income/" hx-target="#content_load">노선별 수지금 현황</a>
                        <a class="aside_a text-black">노선별 수입금 순위</a>
                        <a class="aside_a text-black">운송 수입금 비교표</a>
                    </div>
                </div>
            </div>
            <div class="aside_accordion">
                <button class="aside_btn" type="button">
                    <span class="material-icons custom_arrow">></span>
                    <span class="nav_title">공지사항</span>
                </button>
            </div>


        </div>
    </aside>

<nav id="nav">
    <div id="base_logo_div">
{#        <span id="aside_hide_div" class="material-icons custom_arrow">menu</span>#}
        <span id="aside_hide_div"></span>
        <img id="logo_img" onclick="location.href='/'" src="/static/img/logo.png" alt="logo" title="home">
    </div>

    <div id="nav_right">
        <span id="login_user"><strong>admin</strong></span>
        <button type="button" class="btn btn-sm btn-primary" onclick="confirm('로그아웃 하시겠습니까?')
                                                                    ? location.href=/logout/ : false">logout</button>
    </div>

</nav>

<main id="main">
    <div id="content_div">
        <div id="content_load">

        </div>
    </div>
</main>



<script src="/static/common/event.js"></script>
</body>

</html>