mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from income import views

urlpatterns = [
    # path("users/", include("users.urls")),
    path('admin/', admin.site.urls),
    path('', include("income.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

polls/urls.py
from django.urls import path

from . import views

from django.conf import settings
from django.conf.urls.static import static


app_name = "polls"
urlpatterns = [
    path('', views.index_view.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("create_q/", views.create_q, name="create_q"),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

polls/forms.py
from django import forms
from .models import Question, Choice


class question_form(forms.Form):
    another_question_select = forms.ModelChoiceField(queryset=Question.objects.all(),
                                                     to_field_name='pk',
                                                     empty_label='질문을 선택하세요')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.initial:
            if self.initial.get('queryset'):
                self.fields['another_question_select'] = forms.ModelChoiceField(queryset=self.initial.get('queryset'),
                                                                                to_field_name='pk',
                                                                                empty_label='질문을 선택하세요'
                                                                                )


class choice_form(forms.Form):
    Choice_select = forms.ModelChoiceField(queryset=Choice.objects.all())


class question_model_form(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text']

polls/views.py
from django.http import HttpResponse
from django.views.generic import ListView

from django.views import generic

from general.models import Employee
from .models import Choice, Question
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.db.models import QuerySet
from . import forms
from django.views.generic import TemplateView


class index_view(TemplateView):
    template_name = 'polls/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['emp'] = Employee.objects.all()
        return context


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        if self.queryset is None:
            if self.model:
                return self.model._default_manager.all()
            else:
                return None  # origin : ImproperlyConfigured()

    def get_template_names(self):
        if self.template_name is None:
            return None  # origin :  ImproperlyConfigured()
        else:
            # return None
            return [self.template_name]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['object1'] = Choice.objects.filter()
        context['object2'] = self.model.objects.filter()
        qs = Question.objects.exclude(pk=self.object.pk)
        init = {'queryset': qs}
        context['form'] = forms.question_form(initial=init)
        return context


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"




def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))



def create_q(request):
    if request.method == 'POST':
        form = forms.question_model_form
        if form.is_valid():
            form.save()
    else:
        form = forms.question_model_form
        return render(request, 'create_q.html', {'form': form})

polls/templates/polls/create_q.html
<form action="{% url 'polls:create_q' %}" method="post">
      {% csrf_token %}
<div>
    {{ form }}
</div>
    <button type="submit">
        질문생성
    </button>
</form>

polls/templates/polls/detail.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<form action="{% url 'polls:vote' question.id %}" method="post" class="q1_form">
{% csrf_token %}

<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<button type="submit">투표하기</button>
</form>

{#<hr>#}

<div class="test-box">
    <form id="myForm" method="get" class="test-class">
      {% csrf_token %}
      <div class="q_form">
          <div>
              {{ form }}
          </div>

          <button type="button" onclick="submitForm()">다른 질문으로 이동</button>
      </div>
    </form>
</div>

<script>
  function submitForm() {
    var selectBox = document.getElementById('myForm').querySelector('select');
    var selectedValue = selectBox.value;
    console.log("선택 박스 : " + selectBox);
    console.log("선택값 : " + selectedValue);

    var goto = '{% url "polls:detail" pk=0 %}'.replace('0', selectedValue);

    document.getElementById('myForm').action = goto;

    console.log(goto + "   로 이동")

    document.getElementById('myForm').submit();
  }
</script>

polls/templates/polls/index.html
<h1>index</h1>
<table>
    <thead>
        <tr>
            <th>emp</th>
            <td><a href="/emp/">emp</a></td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <th>설문조사</th>
            <td><a href="/polls/">polls</a></td>
        </tr>
    </tbody>
</table>

polls/templates/polls/index_page.html
<a href="polls/"></a>
<a href="general_app/"></a>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<div>
    object : {{ object }}
</div>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>